export const UPDATE_PLAYER_NAME = "UPDATE_PLAYER_NAME";
export const UPDATE_PLAYER_HOOK = "UPDATE_PLAYER_HOOK";
export const UPDATE_PLAYER_ROLE = "UPDATE_PLAYER_ROLE";
export const UPDATE_PLAYER_CULT = "UPDATE_PLAYER_CULT";
export const UPDATE_PLAYER_ABILITY = "UPDATE_PLAYER_ABILITY";
export const UPDATE_PLAYER_VAMPIRE = "UPDATE_PLAYER_VAMPIRE";
