export const UPDATE_PLAYER_NAME = "UPDATE_PLAYER_NAME";
export const UPDATE_PLAYER_HOOK = "UPDATE_PLAYER_HOOK";
export const UPDATE_PLAYER_IDENTITY = "UPDATE_PLAYER_IDENTITY";
export const UPDATE_PLAYER_CULT = "UPDATE_PLAYER_CULT";
export const UPDATE_PLAYER_ABILITY = "UPDATE_PLAYER_ABILITY";
export const UPDATE_PLAYER_VAMPIRE = "UPDATE_PLAYER_VAMPIRE";

export const ADD_PLAYER = "ADD_PLAYER";
export const REMOVE_PLAYER = "REMOVE_PLAYER";
export const CLEAR_GAME = "CLEAR_GAME";
export const UPDATE_PLAYER = "UPDATE_PLAYER";
